services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.convertx.rule=Host(`convert.${DOMAIN_NAME}`)"
      - "traefik.http.services.convertx.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.convertx.tls=true"
      - "traefik.http.routers.convertx.entrypoints=websecure"
      - "traefik.http.routers.convertx.tls.certresolver=le"

networks:
  proxy:
    name: proxy
    external: true
